# -*- mode: ruby -*-
# vi: set ft=ruby :

# Example Vagrantfile

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # This refers to a local `.box` file which should have been generated by running sets in README.md
  config.vm.box_url = "file://amazonlinux2.box"
  config.vm.box = "amazonlinux2"

  # Vagrant has a default synced folder which you might choose to disable
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # This custom built box is not setup to support updates anyway, hence they are been disabled
  config.vm.box_check_update = false

end
